var seperator = "_";
console.log(seperator.repeat(80));
console.log(6 + 2);
console.log(seperator.repeat(80));
console.log(12 - 4);
console.log(seperator.repeat(80));
console.log(2 * 4);
console.log(seperator.repeat(80));
console.log(32 / 4);
console.log(seperator.repeat(80));
